### PR TITLE
Feature rl 6477393740 product page

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Added working product page that pulls from remote json file. Styled to match mock up. 

## Related Tickets & Documents
- Monday Task #6477393740
- https://blackberg-group.monday.com/boards/1931719392/pulses/6477393740

## QA Instructions, Screenshots, Recordings
Test page

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _site/assets/js/products.js
 - _site/assets/uswds/img/usa-icons/warning.svg
 - _site/products/all-products/index.html
 - assets/uswds/img/usa-icons/warning.svg
 - products/all-products.html
 - _site/assets/css/styles.css
 - _site/assets/sass/styles.scss
 - assets/css/styles.css
 - assets/sass/styles.scss
 - package.json

### CODE REVIEW

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/oam/products/all-products/

Screenshot 2024-04-22 at 1 31 35 PM

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Icons missing (attached)
image

Update menu to include path to "All Products"

**Review by will-bbg — CHANGES_REQUESTED** [review]
- It looks like these Sharepoint images are beefy (700kb+). Let's add the lazy loader for the images.
- The nav dropdown for Products has "All Products" linking to "/products/" please make this page the index of the directory.
- Let's also wrap the image in a link that navigates to the product.
- Make the content align to the top of the image, rather than the center. This follows the mockup's layout.

**Comment by RyanCrux** [comment]
Updated with all requested edits:

Icons missing (attached)
     - Done

Let's also wrap the image in a link that navigates to the product.
     -Done

Make the content align to the top of the image, rather than the center. This follows the mockup's layout.
     - Done

The nav dropdown for Products has "All Products" linking to "/products/" please make this page the index of the directory.
     - Done

It looks like these Sharepoint images are beefy (700kb+). Let's add the lazy loader for the images.
     - Done

**Review by will-bbg — CHANGES_REQUESTED** [review]
Screenshot 2024-04-23 at 3 26 46 PM

Looking good as far as those previous updates. However, it appears there are some css issues. The breadcrumbs are broken and the navigation dropdown arrows are missing.

**Comment by RyanCrux** [comment]
All set for review. I have the page cleaned up and will work this way going forward. I still have an inline style to move the alert text left. I played with flex and margin uswds classes but the .usa-alert .usa-alert-body definitions is specific and overrides. Please let me know if you a class to use that I missed. 
Screenshot 2024-04-24 at 11 50 55 AM

**Review by will-bbg — APPROVED** [review]
We can revisit that alert margin/width issue. Let's get this merged!

**Pull request merged**
