### PR TITLE
feat: add cta to products page

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Added CTA in a banner with white text. Added under the yellow box with an email link.

## Related Tickets & Documents
- Monday Task : https://blackberg-group.monday.com/boards/1931719392/pulses/7689532281

## QA Instructions, Screenshots, Recordings

- Review and approve design (borrowed from OAM homepage)
- test functionality of site with updated banner

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _includes/products/product-list.html
 - _site/products/index.html

### CODE REVIEW

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/oam/products/

@will-bbg 
I borrowed from current design to provide "banner (colored Box with white text)". I placed it below the yellow box as requested. I wanted to run it past you for any design modifications/changes?

**Review by will-bbg — CHANGES_REQUESTED** [review]
I like where you are going with this. What if we change that dark blue to the light blue, adding the class ".bg-primary-lighter" would work.

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/oam/products/

Ready for another look.
Added bg-primary-lighter for the banner. Updated text & button color.

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
