### PR TITLE
feat: setup make up brush page

### PR DESCRIPTION
**Pull request by rb-blackberg**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- Review new article layout, title, and link

https://dev-innovation.bgsandbox.com/oam/news-and-events/makeup-brush-holder/

## Related Tickets & Documents
[- Monday Task #](https://blackberg-group.monday.com/boards/1931719392/pulses/7476043399)

## QA Instructions, Screenshots, Recordings

- Review new article layout, title, and link

https://dev-innovation.bgsandbox.com/oam/news-and-events/makeup-brush-holder/

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _site/assets/img/news-and-events/newsletters/fy24-q4/brenda-guevara-brush-holder.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/brenda-guevara-navy-veteran.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/kelly-saleguero.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/makeup-brush-holder-3d-printed.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/oam-3d-printing-design.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/oam-3d-printing-process.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/oam-holding-3d-printing.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/oam-makeup-brush-holder-3d-design.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/oam-new-generation-makeup-brush-holder.webp
 - _site/assets/img/news-and-events/newsletters/fy24-q4/oam-person-3d-printing.webp
 - _site/news-and-events/makeup-brush-holder/index.html
 - assets/img/news-and-events/newsletters/fy24-q4/brenda-guevara-brush-holder.webp
 - assets/img/news-and-events/newsletters/fy24-q4/brenda-guevara-navy-veteran.webp
 - assets/img/news-and-events/newsletters/fy24-q4/kelly-saleguero.webp
 - assets/img/news-and-events/newsletters/fy24-q4/makeup-brush-holder-3d-printed.webp
 - assets/img/news-and-events/newsletters/fy24-q4/oam-3d-printing-design.webp
 - assets/img/news-and-events/newsletters/fy24-q4/oam-3d-printing-process.webp
 - assets/img/news-and-events/newsletters/fy24-q4/oam-holding-3d-printing.webp
 - assets/img/news-and-events/newsletters/fy24-q4/oam-makeup-brush-holder-3d-design.webp
 - assets/img/news-and-events/newsletters/fy24-q4/oam-new-generation-makeup-brush-holder.webp
 - assets/img/news-and-events/newsletters/fy24-q4/oam-person-3d-printing.webp
 - news-and-events/makeup-brush-holder.html

### CODE REVIEW

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
On mobile, add space above and below each section (as seen on Chrome, Edge) as well as above the image with a blue background
image

**Comment by rb-blackberg** [comment]
Style adjustments have been made based on feedback.

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Still a bit cramped on mobile. In addition to `tablet-lg:padding-y-5`, I'd add padding for mobile, too: `mobile:padding-y-5`

**Comment by rb-blackberg** [comment]
Increased padding on mobile.

**Review by ecstech-admin — APPROVED** [review]
🚀

**Pull request merged**
