### PR TITLE
feat: update news quarterly logic

### PR DESCRIPTION
**Pull request by rb-blackberg**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents
[- Monday Task #](https://blackberg-group.monday.com/boards/1931719392/pulses/7609898258)

## QA Instructions, Screenshots, Recordings
- Verify home page shows articles without dates above them
- Verify news and events page shows articles in each section

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

### CODE REVIEW

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Seem to be different styles on current (left) vs previous (right) articles. More obvious in mobile view: extra space between photo and copy on "Current".
image

**Comment by rb-blackberg** [comment]
> Seem to be different styles on current (left) vs previous (right) articles. More obvious in mobile view: extra space between photo and copy on "Current". image

This is a known issue with the images they are uploading - the space is built into the image.

**Review by ecstech-admin — COMMENTED** [review]
og-title is from Our Team page. Should match page <title>.

Otherwise, good to go

**Comment by rb-blackberg** [comment]
og:title has been updated

**Review by ecstech-admin — APPROVED** [review]
🚀

**Pull request merged**
