### PR TITLE
Feature/jls 6321532050/fellowship development

### PR DESCRIPTION
**Pull request by ecstech-admin**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [x] Optimization
- [ ] Documentation Update

## Description
New OAM Fellowship page

## Related Tickets & Documents
- Monday Task #6321532050
- https://blackberg-group.monday.com/boards/1931719392/pulses/6321532050

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _includes/fellowships/3d-printing-fellowship.html
 - _includes/fellowships/alumni.html
 - _includes/fellowships/current-fellows.html
 - _includes/fellowships/empower.html
 - _includes/fellowships/page-title.html
 - _site/assets/img/decore/triangle-fellow-empower.svg
 - _site/assets/img/fellowships/alyssa-habermann.png
 - _site/assets/img/fellowships/alyssa-habermann.webp
 - _site/assets/img/fellowships/graham-gardner.png
 - _site/assets/img/fellowships/graham-gardner.webp
 - _site/assets/img/fellowships/oam-fellowship-intro.png
 - _site/assets/img/fellowships/oam-fellowship-intro.webp
 - _site/assets/img/fellowships/yu-hui-huang.png
 - _site/assets/img/fellowships/yu-hui-huang.webp
 - _site/assets/sass/vha/pages/fellowships/_index.scss
 - _site/assets/sass/vha/pages/fellowships/fellowship.scss
 - _site/fellowships/index.html
 - assets/img/decore/triangle-fellow-empower.svg
 - assets/img/fellowships/alyssa-habermann.png
 - assets/img/fellowships/alyssa-habermann.webp
 - assets/img/fellowships/graham-gardner.png
 - assets/img/fellowships/graham-gardner.webp
 - assets/img/fellowships/oam-fellowship-intro.png
 - assets/img/fellowships/oam-fellowship-intro.webp
 - assets/img/fellowships/yu-hui-huang.png
 - assets/img/fellowships/yu-hui-huang.webp
 - assets/sass/vha/pages/fellowships/_index.scss
 - assets/sass/vha/pages/fellowships/fellowship.scss
 - fellowships/index.html
 - _site/assets/css/styles.css
 - _site/assets/sass/vha/pages/_index.scss
 - assets/css/styles.css
 - assets/sass/vha/pages/_index.scss

### CODE REVIEW

**Comment by will-bbg** [comment]
Hi Jim! I'm looking to review your PR but can't view it on Dev (https://dev-innovation.bgsandbox.com/oam/fellowships/)

**Comment by RyanCrux** [comment]
Looking really good!

I found a few small issues that were different from the mock up.

My screenshots below show the web browser and the figma mock up in each image

Below: spacing under blue box looks to be twice the height in the mock up to what is on sandbox
Screenshot 2024-04-25 at 4 04 57 PM

Below:padding around the text in this blue box isn't as large as the mock up
Screenshot 2024-04-25 at 4 05 58 PM

Below: Photographs down scale to full width on mobile view
Screenshot 2024-04-25 at 4 06 37 PM

Below: This one doesn't seem like it would be as important but the light blue background element doesn't cut though the foreground assets in the same way as the design.
Screenshot 2024-04-25 at 4 07 28 PM

**Review by RyanCrux — CHANGES_REQUESTED** [review]
Changes requested in an inline comment.

**Comment by ecstech-admin** [comment]
Looks great. Ready to merge.

**Pull request merged**
